### ISSUE TITLE
Need to "soft code" trap #s which species were never caught in

### ISSUE THREAD

**Issue by nthaydt** [djhocking/co_canal_turtles#6]
commit: c4b3f18eb37cf0badf6ee8c67ed1c138dfeb43f0

"Code/prep_prub_data.R"

Lines 117 - 119: Adds in trap # for which no individuals were caught (at any site), but will only work for PRUB. Need to edit so populates excess traps per species (not just for PRUB).

**Comment by djhocking** [comment]
I don't understand what this code is trying to achieve or why it would be different for PRUB compared with the code from CPIC. We didn't get CPIC in every trap.

**Comment by nthaydt** [comment]
For the EM_array (line 199), the em_wide object would not work unless I had at least 1 individual per trap number (we end up expanding by trap and day). There were some trap #’s that PRUB was not caught in between all sites. CPIC wasn’t caught in every trap per site, but was caught at each trap # at least once if you combined all sites.

- Natalie

**Comment by djhocking** [comment]
Ah, ok. The solution is with expand.grid (or the tidy version) but using all the sites, traps, days from the data, not filtered by species, to get all the unique combinations. It's best to have the observation data that includes all that separate from the capture histories for this very purpose.

I'll give it a try now.

**Comment by djhocking** [comment]
Got it working I believe. Pushed to github. The crux was:

```
EM_expanded <- combo_site_trap_day %>%
  left_join(EM) %>%
  ungroup() %>%
  expand(nesting(site_num, ind, id_site), trap, day) %>%
  left_join(EM) 
```
The first left join is necessary for the nesting but it strips out the other data so the second left join brings back the sex and other individual data. Most of this is necessary because different sites have different numbers of traps. Another strategy might have been to do by site then bind the results together.
